config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :items
  resources :categories
  resources :publishers

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  belongs_to :publisher
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:item_type, :isbn, :grade_level, :status, :category_id, :author, :publisher_id)
    end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :set_publisher, only: [:show, :edit, :update, :destroy]

  def index
    @publishers = Publisher.all
  end

  def show
  end

  def new
    @publisher = Publisher.new
  end

  def edit
  end

  def create
    @publisher = Publisher.new(publisher_params)

    respond_to do |format|
      if @publisher.save
        format.html { redirect_to @publisher, notice: 'Publisher was successfully created.' }
        format.json { render :show, status: :created, location: @publisher }
      else
        format.html { render :new }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @publisher.update(publisher_params)
        format.html { redirect_to @publisher, notice: 'Publisher was successfully updated.' }
        format.json { render :show, status: :ok, location: @publisher }
      else
        format.html { render :edit }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @publisher.destroy
    respond_to do |format|
      format.html { redirect_to publishers_url, notice: 'Publisher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_publisher
      @publisher = Publisher.find(params[:id])
    end

    def publisher_params
      params.require(:publisher).permit(:name, :website)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def active_link(link)
    controller_name == link ? "active" : ""
  end

end

app/views/categories/_form.html.haml
= form_for(@category, html: {class: 'form-horizontal'}) do |f|
  %fieldset
    - if @category.errors.any?
      .alert.alert-danger.alert-dismissible
        %button.close{"data-dismiss"=>"alert", "aria-label"=>"Close"}>
          %span{"aria-hidden"=>"true"} &times;
        = pluralize(@category.errors.count, "error")
        prohibited this item from being saved:
        %ul
          - @category.errors.full_messages.each do |message|
            %li= message
    .form-group
      = f.label :name, class: 'control-label'
      = f.text_field :name, class: "form-control"
    .form-group
      = f.label :description, class: 'control-label'
      = f.text_field :description, class: "form-control"
    .form-group.text-center
      = f.submit "Create Category", class: "btn btn-primary"

app/views/categories/edit.html.haml
.container
  .row
    .col-lg-6.col-sm-6.col-lg-offset-2.col-sm-offset-2.well
      %legend.text-center Editing category
      = render 'form'

app/views/categories/index.html.haml
.container
  %p#notice= notice
  %h1 Categories
  .table-responsive
    %table.table
      %thead
        %tr
          %th Name
          %th Description
          %th{:colspan => "3"}
      %tbody
        - @categories.each do |category|
          %tr
            %td= link_to category.name, category
            %td= category.description
            %td
              = link_to 'Edit', edit_category_path(category), class: "btn btn-primary btn-xs"
              = link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-xs"
    %br/
    = link_to 'New Category', new_category_path, class: "btn btn-primary"

app/views/categories/new.html.haml
.container
  .row
    .col-lg-6.col-sm-6.col-lg-offset-2.col-sm-offset-2.well
      %legend.text-center New Category
      = render 'form'

app/views/categories/show.html.haml
.container
  .row
    .col-lg-6.col-sm-6.col-lg-offset-2.col-sm-offset-2.well
      - if notice
        .alert.alert-info.alert-dismissible
          %button.close{"data-dismiss"=>"alert", "aria-label"=>"Close"}>
            %span{"aria-hidden"=>"true"} &times;
          = notice
      %ul.list-group
        %li.list-group-item
          %strong Name
          = @category.name
        %li.list-group-item
          %strong Description
          = @category.description
        %li.list-group-item
          %strong Items
          = @category.items.map(&:item_type).uniq.join(', ')
      = link_to 'Edit', edit_category_path(@category)
      |
      \#{link_to 'Back', categories_path}

app/views/home/index.html.haml
.container.pad-top-10
  .row
    .col-lg-8.col-sm-8.col-lg-offset-2.col-sm-offset-2.jumbotron.text-center 
      %h1 
        Homeschool 
        .small Resource Library
      - if current_user
        = link_to "Browse Items", items_path, class: "btn btn-primary btn-lg"
      - else 
        = link_to "Log in", new_session_path(resource_name), class: "btn btn-primary"
        = link_to "Sign up", new_registration_path(resource_name), class: "btn btn-primary"
        %h5
          .small= link_to "Forgot your password?", new_password_path(resource_name)

app/views/items/_form.html.haml
= form_for(@item, html: {class: 'form-horizontal'}) do |f|
  - if @item.errors.any?
    .alert.alert-danger.alert-dismissible
      %button.close{"data-dismiss"=>"alert", "aria-label"=>"Close"}>
        %span{"aria-hidden"=>"true"} &times;
      = pluralize(@item.errors.count, "error")
      prohibited this item from being saved:
      %ul
        - @item.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :item_type, class: 'control-label' 
    = f.text_field :item_type, class: "form-control"
  .form-group
    = f.label :isbn, class: 'control-label' 
    = f.number_field :isbn, class: "form-control"
  .form-group
    = f.label :grade_level, class: 'control-label' 
    = f.text_field :grade_level, class: "form-control"
  .form-group
    = f.label :status, class: 'control-label' 
    = f.text_field :status, class: "form-control"
  .form-group
    = f.label :author, class: 'control-label' 
    = f.text_field :author, class: "form-control"
  .form-group
    = f.label :category, class: 'control-label'
    = select_tag "item[category_id]", options_from_collection_for_select(Category.all, :id, :name), prompt: 'Select Category', class: "form-control "
  .form-group
    = f.label :publisher, class: 'control-label'
    = select_tag "item[publisher_id]", options_from_collection_for_select(Publisher.all, :id, :name), prompt: 'Select Publisher', class: "form-control"
  .form-group.text-center
    = f.submit "Create Item", class: "btn btn-primary"

app/views/items/edit.html.haml
.container
  .row
    .col-lg-6.col-sm-6.col-lg-offset-2.col-sm-offset-2.well
      %legend.text-center Editing Item
      = render 'form'

app/views/items/index.html.haml
.container
  %p#notice= notice
  %h1 Items
  .table-responsive
    %table.table
      %thead
        %tr
          %th Item type
          %th Isbn
          %th Grade level
          %th Status
          %th Category
          %th Author
          %th Publisher
          %th{:colspan => "3"}
      %tbody
        - @items.each do |item|
          %tr
            %td= link_to item.item_type, item
            %td= item.isbn
            %td= item.grade_level
            %td= item.status
            %td= item.category.name if item.category
            %td= item.author
            %td= item.publisher.name if item.publisher
            %td
              = link_to 'Edit', edit_item_path(item), class: "btn btn-primary btn-xs"
              = link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-xs"
  %br/
  = link_to 'New Item', new_item_path, class: "btn btn-primary"

app/views/items/new.html.haml
.container
  .row
    .col-lg-6.col-sm-6.col-lg-offset-2.col-sm-offset-2.well
      %legend.text-center New Item
      = render 'form'

app/views/items/show.html.haml
.container
  .row
    .col-lg-6.col-sm-6.col-lg-offset-2.col-sm-offset-2.well
      - if notice
        .alert.alert-info.alert-dismissible
          %button.close{"data-dismiss"=>"alert", "aria-label"=>"Close"}>
            %span{"aria-hidden"=>"true"} &times;
          = notice
      %ul.list-group
        %li.list-group-item
          %strong Item type:
          = @item.item_type
        %li.list-group-item
          %strong Isbn:
          = @item.isbn
        %li.list-group-item
          %strong Grade level:
          = @item.grade_level
        %li.list-group-item
          %strong Status:
          = @item.status
        %li.list-group-item
          %strong Category:
          = @item.category.name if @item.category
        %li.list-group-item
          %strong Author:
          = @item.author
        %li.list-group-item
          %strong Publisher:
          = @item.publisher.name if @item.publisher
      = link_to 'Edit', edit_item_path(@item)
      |
      \#{link_to 'Back', items_path}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/ 
    %meta{charset: "utf-8"}/
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }
    
    %title Hslibrary
    
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  
  %body
    
    = render 'shared/main_nav'
    
    .container-fluid
      
      = yield

app/views/publishers/_form.html.haml
= form_for(@publisher, html: {class: 'form-horizontal'}) do |f|
  - if @publisher.errors.any?
    .alert.alert-danger.alert-dismissible
      %button.close{"data-dismiss"=>"alert", "aria-label"=>"Close"}>
        %span{"aria-hidden"=>"true"} &times;
      = pluralize(@publisher.errors.count, "error")
      prohibited this item from being saved:
      %ul
        - @publisher.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :name, class: 'control-label' 
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :website, class: 'control-label' 
    = f.text_field :website, class: "form-control"
  .form-group.text-center
    = f.submit "Create Publisher", class: "btn btn-primary"

app/views/publishers/edit.html.haml
.container
  .row
    .col-lg-6.col-sm-6.col-lg-offset-2.col-sm-offset-2.well
      %legend.text-center  Edit Publisher
      = render 'form'

app/views/publishers/index.html.haml
.container
  %p#notice= notice
  %h1 Publishers
  .table-responsive
    %table.table
      %thead
        %tr
          %th Name
          %th Website
          %th{:colspan => "3"}
      %tbody
        - @publishers.each do |publisher|
          %tr
            %td= link_to publisher.name, publisher
            %td= publisher.website
            %td
              = link_to 'Edit', edit_publisher_path(publisher), class: "btn btn-primary btn-xs"
              = link_to 'Delete', publisher, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-xs"
    %br/
    = link_to 'New Publisher', new_publisher_path, class: "btn btn-primary"

app/views/publishers/new.html.haml
.container
  .row
    .col-lg-6.col-sm-6.col-lg-offset-2.col-sm-offset-2.well
      %legend.text-center New Publisher
      = render 'form'

app/views/publishers/show.html.haml
.container
  .row
    .col-lg-6.col-sm-6.col-lg-offset-2.col-sm-offset-2.well
      - if notice
        .alert.alert-info.alert-dismissible
          %button.close{"data-dismiss"=>"alert", "aria-label"=>"Close"}>
            %span{"aria-hidden"=>"true"} &times;
          = notice
      %ul.list-group
        %li.list-group-item
          %strong Name
          = @publisher.name
        %li.list-group-item
          %strong Website
          = @publisher.website
        %li.list-group-item
          %strong Items
          = @publisher.items.map(&:item_type).uniq.join(', ')
      = link_to 'Edit', edit_publisher_path(@publisher)
      |
      \#{link_to 'Back', publishers_path}

app/views/shared/_main_nav.haml
%nav.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      %a.navbar-brand.pad-top-10.text-center{:href => root_path}
        %span.glyphicon.glyphicon-book{"aria-hidden" => "true"}
        Homeschool 
        .small Resource Library
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{class: active_link('home')}
          = link_to 'Home', root_path
        %li{class: active_link('items')}
          = link_to 'Items', items_path
        %li{class: active_link('publishers')}
          = link_to 'Publishers', publishers_path
        %li{class: active_link('categories')}
          = link_to 'Categories', categories_path
      %ul.nav.navbar-nav.navbar-right
        = render 'devise/shared/links'